- web/problems/models.py
- web/problems/templates/python/attempt.py
- web/problems/templates/python/check.py
- web/utils/__init__.py
Kako se vam zdi? Zaenkrat je datoteko treba zgenerirati z
from problems.models import Problem
from users.models import User
p = Problem.objects.get(pk=1)
u = User.objects.get(username='lokar')
with open('user.py', 'w') as f:
f.write(p.attempt_file(u).encode('utf-8'))
> Attempt Python script

- web/attempts/rest.py
- web/problems/rest.py
- web/utils/rest.py
Sedaj deluje takole:
- vedno naredis POST na /problems/submit/
- ce problem nima id-ja, potem se problem in deli ustvarijo na novo (id delov se ignorira)
- ce problem ima id:
* parti brez id-ja se ustvarijo na novo
* parti, ki so v basi in niso omenjeni v podatkih se izbrisejo
* preostali parti se posodobijo.
Nazaj se poslje 400 BAD REQUEST (+ opis napake) v primeru napake in 200 OK (+ zadnji podatki o problemu v JSON obliki).
> Teacher problem post

- web/attempts/admin.py
- web/attempts/migrations/0004_historicalattempt.py
- web/attempts/models.py
- web/attempts/rest.py
- web/problems/admin.py
- web/problems/migrations/0003_historicalpart_historicalproblem.py
- web/problems/models.py
- web/requirements/local.txt
- web/web/settings/dev.py
- web/web/settings/local.py
Namestil in konfiguriral sem django-simple-history. 
Preveril sem, da se v adminu beleži uporabnik ki je naredil spremembe, tip spremembe  in kdaj je bila narejena.
> Simple history

- web/problems/rest.py
Respect sort order defined in the python file.
> Respect sort order

- web/problems/templates/python/edit.py
> Upload templates.

- web/problems/templates/python/edit.py
If there is no template then strip_hashes gets `None`.
> Fix empty templates.

- web/problems/templates/r/attempt.r
Tukaj je popravek za #137. Problem je bil, da so se prazne rešitve poslale na strežnik - ker se lokalni testi niso pognali, je bila prazna naloga označena za pravilno, če ni bilo secretov. Zdaj bi moralo delovat pravilno.
> Do not send empty solutions (closes #137)

- web/problems/models.py
- web/problems/views.py
Sem dodal še nastavitev MIME tipa za pobrane skripte - da ne bo pisalo, da gre za Pythonovo skripto, če to ni.
> Add per-language MIME types

- web/templates/problems/solutions.html
- web/utils/static/css/tomo.css
Sem pripravil popravek za #140. @matijapretnar, @lokarM, kako se vama zdi?
> Add solution validity indicator in code review

- web/problems/models.py
Sedaj se prikazuje zgolj aktivne študente, kot je željeno v #143.
> Progress showing filter

- web/problems/templates/python/check.py
- web/problems/templates/r/check.r
Tukaj je še preostala funkcionalnost iz #172, z izjemo `check$input`, saj nisem našel načina, kako bi v R preusmeril standardni vhod.
> File and output checking in R

- web/problems/models.py
- web/problems/templates/octave/attempt.m
- web/problems/templates/octave/check_functions.m
- web/problems/templates/octave/edit.m
- web/problems/templates/octave/utils.m
Changed Octave language to support Matlab as well. This is at request from Bor Plestenjak. I could not test it, as I have no matlab available.
> Matlab support

- web/problems/templates/octave/attempt.m
- web/problems/templates/octave/check_functions.m
- web/problems/templates/octave/edit.m
There were some incompatibilities left in Octave templates, as  well as bugs in previous PR. This PR only affect octave/matlab support.
> Matlab support corrections

- web/README.md
- web/requirements/sqlite_local.txt
- web/web/settings/sqlite_local.py
Predlagam kratka navodila za postavitev lokalnega strežnika namenjenega testiranju. Da ni treba opletati s postgres strežnikom, sem pripravil še dodatne nastavitve za sqlite3.
> Testing guide

- web/problems/templates/octave/attempt.m
- web/problems/templates/octave/check_functions.m
- web/problems/templates/octave/edit.m
- web/problems/templates/octave/jsonlab.m
- web/problems/templates/octave/utils.m
Zamenjal sem narekovaje in odstranil šumnike.  Spremenjene so le template datoteke za octave. Ako ima kdo katere manj nerodne zamenjave za stavke s krilatimi znaki, se veselim njegove asistence.
> Matlab support x

- web/templates/base.html
> Popravil footer.

- .gitignore
- README.md
- web/README.md
navodila v readme posodobljena še za Windows. Na README v root sem dodal link na navodila. Virtual environment, kot je v navodilih sem dodal v gitignore.
> Boljsa navodila v README in gitignore

- web/courses/models.py
- web/templates/courses/_problem_set.html
- web/templates/problems/solutions.html
Uredil sem vse tri zadeve, omenjene v #194, našel še eno (prikaz rešitev) in malenkostno polepšal kodo.
Closes #194
> Dodaj podporo za PROBLEM_HIDDEN

- web/templates/problems/solutions.html
Add missing tag around hard-coded slovenian string and translate string to english.
> Add missing trans tag

- web/templates/courses/course_progress.html
- web/templates/courses/problem_set_progress.html
- web/templates/problems/solutions.html
- web/utils/static/css/tomo.css
Fixes #208.  Dodal predlagane ikone, zaenkrat so privzete. Če se bo izkazalo, da so moteče, se lahko kasneje doda možnost izklopa le teh.
Popravil sem še napačno podčrtovanje krogcev.
> Popravil nezaželjeno podčrtavanje in dodal grafične ikone.

- web/templates/help_teachers.html
Co-authored-by: Katja Bukovec <katja.bukovec@student.fmf.uni-lj.si>.
> Reformat and change ` to <code> tags.

- web/locale/sl/LC_MESSAGES/django.po
- web/problems/models.py
- web/templates/courses/course_detail.html
Če je predmet prazen sem učencem pustil sporočilo. Potrebno je dodati še prevode.
> Sporočilo pri predmetu brez sklopov.

- .gitignore
- web/.gitignore
- web/courses/admin.py
- web/courses/migrations/0015_institution.py
- web/courses/models.py
- web/templates/homepage.html
> Move Institution to a foreign key.

- web/templates/problems/solutions.html
- web/utils/static/css/tomo.css
Closes #74.
Opustimo idejo o enaki višini box-ov za kodo, in se samo potrudimo, da poravnamo zgornji rob.
Potem pade stran en kup CSS-ja in vse se obnaša lepo brez prekrivanja.
> Fix solution display.

- web/courses/models.py
- web/courses/views.py
- web/problems/models.py
- web/templates/courses/_problem_set.html
- web/templates/courses/problem_set_detail.html
Optimiziranih več pogledov za učitelje:
-osnovna stran
-stran predmeta
-nabor problemov
> Optimizacije vmesnika za učitelje

- web/courses/views.py
> Sort institutions alphabetically

- web/attempts/rest.py
- web/courses/rest.py
- web/problems/rest.py
Zaprl privzete akcije, ki jih viewset podeduje od ModelViewSet (list, retrieve, create, update, delete).
> closed default viewset actions

- web/problems/templates/python/attempt.py
Da lažje ugotovimo, s čim imajo študenti težave.
> Boljše poročanje napak pri neuspešnem shranjevanu zaradi težav s povezavo

- README.md
Also made the OS-specific instructions have consistent order.
> Correct Linux venv activation instruction

- web/courses/models.py
CourseGroups are now sorted by title, description.
Closes #238
> Sort coursegroups

- .github/workflows/test.yml
- pyproject.toml
- web/courses/admin.py
- web/courses/views.py
- web/templates/problems/solutions.html
- web/tomo_statistics/statistics_utils.py
Closes #160 
V značko, ki prikaže rešitev naloge sem dodal razred "tex2jax_ignore".
> Mathjax ignorira rešitve nalog

- web/templates/courses/problem_set_detail.html
- web/utils/static/css/tomo.css
Pravilnost rešitve se označi s pobarvanim levim robom podnaloge. 
Barve so identične kot v krogcih na desnem delu strani.
Zapre #76.
> Pobarvan levi rob podnaloge v odvisnosti od pravilnosti rešitve

- web/attempts/admin.py
- web/courses/admin.py
- web/problems/admin.py
- web/users/models.py
> Admin goodies

- web/templates/courses/course_detail.html
- web/templates/statistics/compare_solutions_problems.html
- web/templates/statistics/compare_solutions_timeline.html
- web/templates/statistics/contents.html
- web/tomo_statistics/urls.py
- web/tomo_statistics/views.py
Pogled za lažji pregled prepisovanja in podobnosti rešitev. Na voljo časovnica oddaj 2eh učencev za posamezen sklop razvrščen po vrstnem redu oddaj in pa pogled rešitev dveh učencev za vsako nalogo v sklopu ena ob drugi.
> Supervision
